[tool.poetry]
name = "sebaubuntu_libs"
version = "1.0.3"
description = "SebaUbuntu's shared libs"
authors = ["Sebastiano Barezzi <barezzisebastiano@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/SebaUbuntu/sebaubuntu_libs"

[tool.poetry.dependencies]
python = "^3.9"
GitPython = "^3.1.27"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
